export const ROUTES = {
  HOME: '/',
  DASHBOARD: '/',
  FEEDBACK: '/feedback',
  MEMORY: '/memory',
  MEMORY_RECALL: '/memory/recall',
  MEMORY_REFLECT: '/memory/reflect',
  MEMORY_MODELS: '/memory/models',
  MEMORY_EVOLUTION: '/memory/evolution',
  MEMORY_GRAPH: '/memory-graph',
  THEMES: '/themes',
  INSIGHTS: '/insights',
  TRENDS: '/trends',
  RECOMMENDATIONS: '/recommendations',
  FEATURES: '/features',
  ISSUES: '/issues',
  REPORTS: '/reports',
  WORKSPACE: '/workspace',
  INTEGRATIONS: '/integrations',
  SETTINGS: '/settings',
  LOGIN: '/login',
};
